"""empty message

Revision ID: eae1e292594c
Revises: 9c511584239c
Create Date: 2021-12-07 17:31:13.283885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae1e292594c'
down_revision = '9c511584239c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user_image', ['picture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'picture_id')
    op.drop_table('user_image')
    # ### end Alembic commands ###
